version: '3'

services:
  
  backend:
    build: ./backend
    volumes:
      - ./backend:/code
    ports:
      - 5555:5555
    hostname: backend-service

  web-ui:
    build: ./web-ui
    volumes:
      - ./web-ui:/code
    ports:
      - 8080:8080
    depends_on:
      - web-ui-service