version: '3'

services:
  
  backend:
    build: ./backend
    volumes:
      - ./backend:/code
    ports:
      - 5555:5555
    hostname: backend-service
  
  data-processing:
    build: ./data-processing
    volumes:
      - ./data-processing:/code
    ports:
      - 6666:6666
    hostname: data-processing-service

  web-ui:
    build: ./web-ui
    volumes:
      - ./web-ui:/code
    ports:
      - 8080:8080
    depends_on:
      - backend